//---------------------------------------------------------------------------
#include <vcl\vcl.h>
#pragma hdrstop

#include "MsgBox.h"
//---------------------------------------------------------------------------
#pragma resource "*.dfm"

#define MaxBtn 10


//#define mrAll 8

TMsgDlg *MsgDlg;

int MyMsgBox(AnsiString DlgCaption, AnsiString DlgText,WORD Buttons)
{
   int Retval = -1;
   bool created = false;
   if (MsgDlg == NULL)  //prevent creation if dialog is automatically generated by project
   {
     Application->CreateForm(__classid(TMsgDlg), &MsgDlg);
     created = true;
   }
   MsgDlg->Caption = DlgCaption;
   MsgDlg->LabelText->Caption = DlgText;
   //make Buttons visible
   if ((Buttons & BtnOk) == BtnOk)
     MsgDlg->OkBtn->Visible = true;
   else
     MsgDlg->OkBtn->Visible = false;

   if ((Buttons & BtnCancel) == BtnCancel)
     MsgDlg->CancelBtn->Visible = true;
   else
     MsgDlg->CancelBtn->Visible = false;

   if ((Buttons & BtnYes) == BtnYes)
     MsgDlg->YesBtn->Visible = true;
   else
     MsgDlg->YesBtn->Visible = false;

   if ((Buttons & BtnNo) == BtnNo)
     MsgDlg->NoBtn->Visible = true;
   else
     MsgDlg->NoBtn->Visible = false;

   if ((Buttons & BtnHelp) == BtnHelp)
     MsgDlg->HelpBtn->Visible = true;
   else
     MsgDlg->HelpBtn->Visible = false;

   if ((Buttons & BtnAbort) == BtnAbort)
     MsgDlg->AbortBtn->Visible = true;
   else
     MsgDlg->AbortBtn->Visible = false;

   if ((Buttons & BtnRetry) == BtnRetry)
     MsgDlg->RetryBtn->Visible = true;
   else
     MsgDlg->RetryBtn->Visible = false;

  if ((Buttons & BtnIgnore) == BtnIgnore)
     MsgDlg->IgnoreBtn->Visible = true;
   else
     MsgDlg->IgnoreBtn->Visible = false;

  if ((Buttons & BtnAll) == BtnAll)
     MsgDlg->AllBtn->Visible = true;
   else
     MsgDlg->AllBtn->Visible = false;


   Retval = MsgDlg->ShowModal();

   if (created)
   {
      delete MsgDlg;
      MsgDlg = NULL;
   }
   return Retval;
}
//---------------------------------------------------------------------------
__fastcall TMsgDlg::TMsgDlg(TComponent* Owner)
        : TForm(Owner)
{
}

//---------------------------------------------------------------------------
